{{- /* Stable Service. Rollouts manages rollouts-pod-template-hash here. */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes-app.fullname" . }}
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "notes-app.selectorLabels" . | nindent 4 }}
{{- if .Values.rollout.trafficRouting.enabled }}
---
{{- /* Canary Service. Only needed with traffic routing. */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes-app.fullname" . }}-canary
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "notes-app.selectorLabels" . | nindent 4 }}
{{- end }}
